### ISSUE TITLE
Add "show_in_rest" to custom post types

### ISSUE THREAD

**Issue by danwatt** [churchthemes/church-theme-content#13]
The Wordpress team is working on a "feature as a plugin" that allows for interacting with a Wordpress site via a REST API. Custom post types do not show up by default, but can by simply adding `'show_in_rest' => true` in the arguments to `register_post_type`.

This allows for a sermon to be accessed like so:

GET www.mychurch.example/wp-json/wp/v2/ctc_sermon/8532

``` json
{
  "id": 8532,
  "date": "2015-08-09T12:15:30",
  "guid": {
    "rendered": "www.mychurch.example/?p=7070"
  },
  "modified": "2015-10-14T19:41:14",
  "modified_gmt": "2015-10-15T00:41:14",
  "slug": "gods-plan",
  "type": "ctc_sermon",
  "link": "http://www.mychurch.exampleh/sermons/gods-plan",
  "title": {
    "rendered": "God&#8217;s Plan"
  },
  "content": {
...
  }
}
```

Im working on a tool to port a site containing ~10 years of sermons from vanilla wordpress to a site based on the Exodus theme, which uses the CTC plugin, and the REST API has proven to be invaluable at automating this migration.

**Comment by stevengliebe** [comment]
Hi Dan,

I'm glad you're able to use the REST API for migration. The API will open up a whole world of possibilities.

Right now I'm not sure about flipping `show_in_rest` on for all users by default. I'll reevaluate this sometime after the API is in core. It might be useful to add a setting for users to enable this at will.

In the meantime the filter `ctc_post_type_sermon_args` can be used to set `show_in_rest` as true. This is an example of how the filter can be used to override default arguments for `register_post_type` in the plugin: https://gist.github.com/stevengliebe/2b26a1862854c28b3d07

**Comment by stevengliebe** [comment]
```show_in_rest``` will be ```true``` for all post types in the plugin in the next release. WordPress core does this for the standard post types so it makes sense to do the same for the CPT's now.

**Comment by danwatt** [comment]
Cool!
