### ISSUE TITLE
Series image

### ISSUE THREAD

**Issue by danielmilner** [churchthemes/church-theme-content#18]
Would you be open to adding taxonomy meta for a Series image? If so, I may be able to work on a pull request.

**Comment by stevengliebe** [comment]
I've had a few requests for this and think it's a good idea. As it is now, a plugin had to be used to add it then a child theme to show it, which I'm not sure anybody has even bothered to do.

I haven't looked into the best way to approach this yet. My notes say WordPress 4.4 added taxonomy meta. It could be a good idea to look at how other plugins are approaching this (now that we have term meta) so we can go about it in a standard sort of way, if possible. Justin Tadlock wrote some things about the term meta possibilities and touched on images.

http://themehybrid.com/weblog/introduction-to-wordpress-term-meta

Theme support for the field would have to be considered. Just as a theme can declare support for specific fields on a post type, we'd probably want to setup something similar for declaring support for specific fields on a taxonomy. That would keep the featured image field (and any other future taxonomy meta) from showing as an option on taxonomy terms for themes that don't have any way of showing it on the front end.

Any thoughts on how to best approach this?

**Comment by danielmilner** [comment]
This plugin by John James Jacoby should offer some good insights into how it should be done.

https://wordpress.org/plugins/wp-term-images/

I've written a sermon plugin for my agency that uses CMB2 to handle all of the custom fields, and that is also how we added a series image. I know that this project does not use CMB2, so implementation will be a little different. We have a function for retrieving the sermon image that falls back to the series image if no sermon image is found.

I'm not yet familiar enough with **church-theme-content** or **church-theme-framework** to know all of the areas that this would affect, but we are looking in to discarding our custom solution in order to use something a bit more open.

**Comment by danielmilner** [comment]
Should [ct-meta-box](https://github.com/churchthemes/ct-meta-box) first be modified to handle term meta?

**Comment by stevengliebe** [comment]
That's a good point. It would need be modified too so this is not quite as straightforward as I had hoped it would be. If you want to work at it and make pull requests, I'll look it over. Or, if you want to wait then we should get to it eventually although it is not high priority right now.

You could also do something more temporary and immediate by using a plugin for taxonomy image.

**Comment by danielmilner** [comment]
After thinking it over, I'm not entirely sure that [ct-meta-box](https://github.com/churchthemes/ct-meta-box) would be the appropriate place for the term meta functions. Mostly because there are no meta boxes in regards to terms, just fields. It might be better to create an entirely new class that handles term meta.

For now, I may work on this as an add-on plugin, then see about merging it in once the kinks are worked out. Sort of how WordPress Core handles new features.

I'd like to use a field name that would not change once merged in to this project. Does something like `ctc_sermon_series_image` sound appropriate? Or perhaps something shorter like `ctc_image`?

**Comment by stevengliebe** [comment]
I think you're right about that. I'll have to step back and look at the big picture. This thread will be helpful. Thank you for your thoughts on this.

Your approach sounds good. `ctc_sermon_series_image` is likely since that's in line with the convention used for the post type meta fields (e.g. `_ctc_sermon_video` and not `_ctc_video`). I don't suppose there will ever be an interface for user-provided custom taxonomy fields so we can probably forgo the underscore.

**Comment by JanSichula** [comment]
Hello,

I will keenly watch the developments in this regard. Now in the the meantime, would you please advice us on how to achieve series images with present plug-in capabilities. We really need this feature regardless of how cumbersome it might presently be to achieve.

**Comment by stevengliebe** [comment]
@JanSichula You could try a plugin that adds image support to taxonomies then create a child theme that will cause that image to show where you want.

**Comment by timnolte** [comment]
As I've recently came across your plugin I'd like to point to a plugin I created, for the church website I manage, that does this exact thing. (https://github.com/ndigitals/nds-wp-podcasting) I'm scoping out your plugin to determine how active/open you guys are to outside developers. If it serves me best I may consider migrating my church's website to your plugin, fully intending on offering my own development and user support time to this plugin. The series image is a must have so I will in now way do a migration without it. I too like the idea of feature add-on plugins like WP Core does.

**Comment by JanSichula** [comment]
@timnolte Before we decided to go with this plugin for our new church web site, I have reviewed around five of them. IMHO, this one is most sophisticated and best maintained of those I have checked.

@stevengliebe I would kindly encourage you to embrace timnolte among the plugin contributors. He looks like an experienced fellow. 😊

**Comment by stevengliebe** [comment]
@timnolte Pull requests and feature suggestions are welcome.

As for this particular feature, it is something I intend to add eventually but is not a high priority at the moment. It seems that with the structure of the plugin, it might be a bit more involved than perhaps it would seem (see what @danielmilner and I started discussing). If you want to tackle it then that would be great and I'll be happy to discuss here.

Otherwise, I do intend to get to it at some point.

**Comment by stevengliebe** [comment]
This will be possible with [WP Sermons](https://wpsermons.com).
