### ISSUE TITLE
Discrepancy in plugin functionality when compared with demo site for Exodus church theme

### ISSUE THREAD

**Issue by JanSichula** [churchthemes/church-theme-content#19]
Hello everyone,

let me first introduce myself a little bit. My name is Jan Sichula and I live in capital of Slovak Republic, Bratislava, where I pastor independent Grace Baptist church. I am also a web programming enthusiast with a little background in .NET and C#. Now our present church web site was built some 13 years ago, by another pastor as a hand-coded PHP (address is http://www.nkzba.sk/). It has served us well across those years but the time is ripe for a new modern solution including features like responsive front-end design. As a Bible believing and Bible preaching church, we publish audio recordings of sermons for wide distribution through our web site.
Originally my idea was to implement sermon functionality on top of .NET based solution named Orchard. However, one of our church members gave me advice to have a look at WordPress. Well, what shall I say – it proved to be good advice for why should one reinvent a wheel if it already exists in good shape and form. I love .NET and Orchard but both still need to get a traction among churches. On the other hand, there is a vibrant community of WP users who had successfully used it to implement church web sites. During last four weeks, I was trying to gain overview of existing WP solutions that offer sermon publishing. I have to say that I like your plugin most of all so far. At this period, I am intensely testing your plugin with free compatible theme named “Restful” to ascertain whether it will indeed satisfy our needs. Now it all looks promising but I also have an issue where I kindly ask for your clarification. How is it that a paid theme named “Exodus” offers functionality that I do not see exposed in the plugin at all (as demonstrated at https://demos.churchthemes.com/exodus/)?
In particular, I can’t see any of the following functions exposed in the plugin as I am trying to give it a test ride and yet the Exodus theme features those capabilities:

- No way to assign sermon topics in the plug-in UI.
- No way to assign sermon tags in the plug-in UI.
- No way to assign date when sermon was preached in the plug-in UI. 

Would you please clarify why is that? Or am I missing something?

Best regards and may God bless your valuable efforts for Lord’s churches.
Jan Sichula

P. S. I am fairly new to the world of PHP and WP but once I gain some experience, I will be happy to lend a helping hand and contribute some code. :-)

**Comment by stevengliebe** [comment]
Hi Jan,

Thank you for using the plugin.

Not every theme supports every feature that the plugin offers. I took a look at Restful's code and while it supports the sermon post type, it does not support the topic or tag taxonomies. You can ask ThemeBright if they will add that or consider another theme that has it.

The plugin does not provide a date field since WordPress itself already offers that (the Publish Date). You can choose a date in the past if necessary.

Please let me know if you have any other questions.
