### ISSUE TITLE
Location_type

### ISSUE THREAD

**Issue by tmushkala** [churchthemes/church-theme-content#21]
Hi, 
Would you consider adding this type of taxonomy to the locations post type?

The kind of thing I'm interested in doing is allowing people to filter a set of locations. For example, we are a diocese, and our locations include both churches and schools, as well as church-sponsored organizations like food pantries, etc. so it could be helpful to display them by type, similar to the way People can be categorized into Groups and easily displayed together.

Thank you for your consideration - we're about to switch to the Saved theme, and it's an excellent piece of work you've done. The theme is really well-designed and very customizable. Thank you for that, too!

**Comment by stevengliebe** [comment]
Hi Tracie,

I'm not sure if I'll add this since there has not been any other demand. If that changes, then I'll consider it. Your best bet for now would be to make a plugin that extend Church Theme Content to add the taxonomy. You could then use a child theme to display the terms.
