### ISSUE TITLE
Question: How to include index page for Topics, Books, etc

### ISSUE THREAD

**Issue by thetallweeks** [churchthemes/church-theme-content#22]
Hi, I've taken the Restful theme and am modifying it so that I can support topics.

I added to the "theme support"

```
add_theme_support( 'ctc-sermons', array(
    'taxonomies' => array(
      'ctc_sermon_book',
      'ctc_sermon_series',
      'ctc_sermon_speaker',
      'ctc_sermon_topic' // added
    ),
    'fields'     => array(
      '_ctc_sermon_video',
      '_ctc_sermon_audio',
      '_ctc_sermon_pdf'
    )
  ) );
```

And added a template called taxonomy-ctc_sermon_topic.php

But I can't seem to figure out how to set up a home page for topics. I want to show a list of all the topics like https://demos.churchthemes.com/exodus/sermon-archive/sermon-topics/

I notice that the non-post types don't have an "All" option in the menus like sermons has. So I'm not sure if this is the issue.

My current setup has /archives/sermon-topic/contentment as a valid url and uses the taxonomy-ctc_sermon_topic.php template. But if I try to go to /archives/sermon-topic it is not found.

I've tried creating template files called taxonomy-sermon-topic.php, archive-ctc_sermon_topic.php, taxonomy-sermon-topic.php and nothing seems to work.

Any help would be greatly appreciated.

**Comment by stevengliebe** [comment]
Hello,

Unfortunately I'm not able to spend time assisting with theme development. The plugin registers post types, taxonomies and custom fields in the standard WordPress manner so I recommend consulting the WordPress theme development docs for how you can show this type of content in your child theme.

It may be easier to use a theme that does support what you need, such as the Exodus theme you mentioned as an example. You could also ask the maker of Restful if they are willing to add this feature to their theme or to custom develop it for you.
