### ISSUE TITLE
Reason for &$this references?

### ISSUE THREAD

**Issue by davidshq** [churchthemes/church-theme-content#8]
Wondering if there is a reason for retaining &$this references in code (e.g. church-theme-content.php under __construct)?

**Comment by stevengliebe** [comment]
You're right, & shouldn't be necessary. Do you want to submit a pull request to get credit? Or I can just remove 'em if you don't have the time.

**Comment by davidshq** [comment]
Sure, I'll submit a pull request momentarily. I'm just getting going on
GitHub, so I'll take the credit where I can get it. ;-)

- http://www.davemackey.net/ - A hub for sites covering my eclectic
interests - product reviews, mental illness/health, wargaming, IT,
Christianity, classical literature, etc.

**Comment by stevengliebe** [comment]
Thanks for the contribution, included with 1.3.3.

https://github.com/churchthemes/church-theme-content/releases/tag/1.3.3
